### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/students

###
GET http://localhost:8080/api/v1/students/2

###

POST http://localhost:8080/api/v1/students
Content-Type: application/json

{
  "name": "Bob",
  "techStack": "sql, databases, java, spring"
}

###
DELETE http://localhost:8080/api/v1/students/1

###

PUT http://localhost:8080/api/v1/students/1
Content-Type: application/json

{
  "name": "Nick",
  "techStack": "Java, Javascript"
}